use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'ProjectDo_Example' do
  pod 'ProjectDo', :path => '../'

  target 'ProjectDo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    
#    pod 'NFAToolkit'
    pod 'AutoData'
    pod 'NFASubprojects'
    pod 'SwiftProjects'
    pod 'STRIAPManagerUtils'
    pod 'ProThirdpart'
    
#    pod 'WechatOpenSDK'  , '~> 1.8.6'
  end
end
